version: '3'

services:
  inbound:
    image: nhsdev/nia-mhs-inbound:1.3.3
    ports:
      - "9787:80"
    environment:
      - MHS_LOG_LEVEL=DEBUG
      - MHS_SECRET_PARTY_KEY=VND3J-823806
      - MHS_SECRET_CLIENT_CERT=>
        -----BEGIN CERTIFICATE-----
        MIIE6TCCA9GgAwIBAgIQb36cSg8yJST/72AxX6SIPzANBgkqhkiG9w0BAQsFADBM
        MQswCQYDVQQGEwJHQjEMMAoGA1UEChMDbmhzMQswCQYDVQQLEwJDQTEiMCAGA1UE
        AxMZTkhTIElOVCBBdXRoZW50aWNhdGlvbiBHMjAeFw0yNDEyMjAwOTI4NTZaFw0y
        NzEyMjAwOTU4NTZaMFcxDDAKBgNVBAoTA25oczEQMA4GA1UECxMHRGV2aWNlczE1
        MDMGA1UEAxMsaW50dGlmLWdwMmdwLmNoZWNrdXBoZWFsdGgudGhpcmRwYXJ0eS5u
        aHMudWswggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCIApoeG0Kvu6jv
        nvo4lHCpRn6eEEZUsj+m3cvO2/x/s4NvLWM/VWrioAoeDWGxyfdCUqaedveL4vWa
        5T+EzjyaAj179iW4U7MaIv4bt48t2tQMfefaJsg2ZLA9IyN/VCyO8lRAm/S2QaXH
        DEpiP482VH/Ix+gO3zMQvfs4UnA2kaZ4XH78rrAvVBgEIcMkH1x4vHRrzC3a7+RT
        8A40yP+WNi8TnH7I97Nkp72ecNJ+5FFJEAXyECOyUzZlIB9qZah/+JfBfDsaNsaP
        nW/0WNwIoBRysvvOaBQcD3mfBgA5yw8KdXxfHnAzD6rl2pb/xq7eE7pFmoK+g0v2
        xEZM2iBnAgMBAAGjggG6MIIBtjALBgNVHQ8EBAMCBaAwHQYDVR0lBBYwFAYIKwYB
        BQUHAwEGCCsGAQUFBwMCMG8GCCsGAQUFBwEBBGMwYTAjBggrBgEFBQcwAYYXaHR0
        cDovL29jc3AubmhzLnVrL29jc3AwOgYIKwYBBQUHMAKGLmh0dHA6Ly9wa2kubmhz
        LnVrL2ludC9HMi9hdXRoL05IU0lOVEF1dGhHMi5jcnQwPgYDVR0gBDcwNTAzBgsq
        hjoAiXtlAAMCADAkMCIGCCsGAQUFBwIBFhZodHRwczovL3BraS5uaHMudWsvQ1BT
        MEMGA1UdHwQ8MDowOKA2oDSGMmh0dHA6Ly9jcmwubmhzLnVrL2ludC9nMi9hdXRo
        L05IU0lOVGF1dGhHMl9jMjIuY3JsMCsGA1UdEAQkMCKADzIwMjQxMjIwMDkyODU2
        WoEPMjAyNzAxMjUyMTU4NTZaMB8GA1UdIwQYMBaAFBbHRwSoYMnkXauZ8pT3w94z
        mNQiMB0GA1UdDgQWBBQtnuNRVFSpreGbqRHypQcAVuCM+TAJBgNVHRMEAjAAMBoG
        CSqGSIb2fQdBAAQNMAsbBVYxMC4wAwIEsDANBgkqhkiG9w0BAQsFAAOCAQEAwdQs
        olIMECyyiiaAJTJOrufhxnivHP6kn3dNlzn8FplvjX9bFkPbqWSdXh5i7OP9AERW
        3/xwnxh/ujPVk/fbedkhsrnr5C30uuOWvMjr3PAZP3N9x+w0L6rVc2V69vrpQWMD
        4AaNu2U5OMvUt8v+jjalWUCkP6tgdGGiLHP6lvV+rj1v53eGq8StyToN8dX1KLIj
        U8EVCqqjZVZsCISIeqPGcOajfP+U8EdVya3tKo0ylkOXmrs4v6BhNBTshlLvq64O
        Kjso1ZQ0m6VxUe5iHV2j5WZwb5SJxWykGaPrHRW6MrJ7VIA2Ab3p1kWeCZ5rR5by
        VA0ghAXQOmLnO46+PQ==
        -----END CERTIFICATE-----
      - MHS_SECRET_CLIENT_KEY=>
        -----BEGIN PRIVATE KEY-----
        MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCIApoeG0Kvu6jv
        nvo4lHCpRn6eEEZUsj+m3cvO2/x/s4NvLWM/VWrioAoeDWGxyfdCUqaedveL4vWa
        5T+EzjyaAj179iW4U7MaIv4bt48t2tQMfefaJsg2ZLA9IyN/VCyO8lRAm/S2QaXH
        DEpiP482VH/Ix+gO3zMQvfs4UnA2kaZ4XH78rrAvVBgEIcMkH1x4vHRrzC3a7+RT
        8A40yP+WNi8TnH7I97Nkp72ecNJ+5FFJEAXyECOyUzZlIB9qZah/+JfBfDsaNsaP
        nW/0WNwIoBRysvvOaBQcD3mfBgA5yw8KdXxfHnAzD6rl2pb/xq7eE7pFmoK+g0v2
        xEZM2iBnAgMBAAECggEALzUP/yEhHVO6SCla2iaTj/161yv47U7NDwLuyYbLdht9
        pCoRx5rDNZOsz09/uDDMlIWRdXD/bNtCuheV22el2yKp6ou9/eN3R7wbjM1Ccf0B
        GrDct3g8h7yc+ytmF7zElnz/x0kaP+Q7QQJAEyfScl4T2EGihv7rf4UhXCQo9JdJ
        pP7samlCIBy4gApB0Tlfs8TRHqUF4Z2iBnEhgRwkGpzKasVwWX4vQYrLtIAQY4jS
        /3NX8yairawWcm4xOnQ+wQN5d83KUrIxOXx7jTHbR9fV5nDPcsKME61jIeVxnPA3
        z6Y/rZzt5Qj7jBX+5vsl1Fdi+3cNnRzt5NY3YgbrgQKBgQDAHjpfj5fH5Lhuvgi8
        oitKH2EX78FWTnZHYWpcM8r9s2lHPyPBTvP+mnuVGQu3/+8dWHpOwFtTAGqBCXQF
        PtMaKPwR5H8PdDijIiaBPOjHpZxpUm5MP0VIf6XOfds/FzCzMPW3P8hN1NEGoHDL
        vITlHrw/WSHcNCiT7hivHxXAJwKBgQC1PET49JU1JHU7fdH3wlkUSH4Ax6WMSNTS
        R8KR8BekYJcThhlKqWZonOhK4H1BnsKHxPtqY8UReImevhVVSApVG+7SMpMQbiHW
        c8gQVimzmpBcSXwL7WyGDqv4I5pKFWdVvXPwKP88D9xAKfsHrPqKJ8/z/LXzkuPl
        iZBRrmCFwQKBgAHsS4lJVquZjn8NR+kbdnN3fPFQZQ8IGgb84qOpoQ6JDTS5XRJC
        SA70XOhRJ9zfovUYPaEsK73Y8zf3cEHdLx/D6UIEl4EAGNEJNnl0sp/M+JPVT2VT
        /M2M+Yvnlpo7ETG5+7up18dvqef3Eyn26R2iASBhNAWQQBe6+mRGW2FhAoGAX8Vh
        jU1yK4sAiFeMxShmell0fGUEDoXOMPDK2OPPGoYQT7jlVJcADvgbqLXIewyyL5zg
        XvAqC3lu//viuhY/n4oLQfiHzn7kUrcMWdWuY8Kh1qLeck8cshq+tXna5ps46A4d
        XiPL/KlE8oM8rGm0W51+PqikXfqZg4qWQROs3gECgYEAkww0f664tHWZKxVk4AS4
        LOjdR6ym3hjdnZ8AyqnaApOuFIVpGTqvPYFXmpWMnnjnRcGcbwa5hiAoULPhSEtZ
        akPPgugh/WOBP3AWZGXTjh+bqg67JAeNS6Um7SEJDjgQOQNCsJLZK1AX5kI6LD+M
        8ReV7171ZJKS5bt7G1OE7WA=
        -----END PRIVATE KEY-----
      - MHS_SECRET_CA_CERTS=>
        -----BEGIN CERTIFICATE-----
        MIIFtDCCA5ygAwIBAgIQHJP1UsE9cdiw+4IqFnxM3TANBgkqhkiG9w0BAQwFADBM
        MQswCQYDVQQGEwJHQjEMMAoGA1UEChMDbmhzMQswCQYDVQQLEwJDQTEiMCAGA1UE
        AxMZTkhTIFBUTCBSb290IEF1dGhvcml0eSBHMjAeFw0yMjA4MDIxNTE3MjRaFw00
        MjA4MDIxNTQ3MjRaMEwxCzAJBgNVBAYTAkdCMQwwCgYDVQQKEwNuaHMxCzAJBgNV
        BAsTAkNBMSIwIAYDVQQDExlOSFMgUFRMIFJvb3QgQXV0aG9yaXR5IEcyMIICIjAN
        BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwIy5AVQWAT35rfI0AYCql2F04Yp9
        M6gTgv6vmxtdHsIJgLCrbxy5p6hQIxCu0Jq4Fc8rflv5jDZOPO6tsFRuJck1Xv17
        53jBAuo00Q0XoORdfTymktLp78P2zNvj3Y3oaXUW6dzwztQf/BLjSwD0A3uuiej8
        BuemHDQDCWHhfu8fkVC85n8XPO1QKzmpTHXBK5tgx5SkDzfxk3zsc31tgs+/xRmZ
        Jc45qWQazFCtGr5rpeKb/9thi9+LbctCMO2Be4La4u6rePOhR8zx73zpLnrtOD8s
        Nfxqk59vyIZ7fqfGCfIs8hdcQFOvfABalSaW2Bg4njwOY879WjyxtE1jpPB/fuDp
        /cQtrdNVLEY+fEa+WBbX/TG2GAQFFle/ThU+c2mtkfToRL42Hrbzfqg9wr69e2oI
        79cQ3DKP1Eaq0bzw8TkOfswoKgKm4QGlBzJFAWaAEvisX+JgRtPzvSTMCttUbBYp
        NnfXwayQ8s9IwYwPeFDQrs0/MR+uUqtObUv9B3T4bNBXoIc98rn7+/x5yQhGYre8
        0YzcqeL33A/K6Tzu+P3u9DftfkOgcnZyg69ePqAAjrY9OA2RqnVfxm7vraaEgxMm
        rpslCni/FM+/P6yV4LdnDJuKfaMq0k+RfkbsT2WXsJHLIec8uRgpoa74QvEO/p85
        UDIFBUds0QqN1GsCAwEAAaOBkTCBjjAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/
        BAUwAwEB/zArBgNVHRAEJDAigA8yMDIyMDgwMjE1MTcyNFqBDzIwNDIwODAyMTU0
        NzI0WjAfBgNVHSMEGDAWgBT1ttVSqL14/nJhaztdjCPAsBYM8zAdBgNVHQ4EFgQU
        9bbVUqi9eP5yYWs7XYwjwLAWDPMwDQYJKoZIhvcNAQEMBQADggIBAKekcO9zq3ER
        YFOJTDqkY4NoDSTmlab4Al07hLJ8WYckSePQ9HmxVEqnTVYBCtPHfcyUlUqbBQVh
        DBQ2ZzERONqq2ENevGh6Li/0ZxuPiQhb5hxL7uv20vTEmbkSrPYs5TKYNbkJ8gx+
        JT4uoxETLfNHG6WvGV2VBbMR+dZQisRoR0jm8P7n7wkTHjiDNH7FLfgozy3hIfUR
        0bhLEt3HlniPBoC4egvZMP/R8rnOwqdEmStP6YR2BZxUSmrQozOamVJIljMTiTlG
        xwqmvVMnRtaYIQsdOyiXpS4UjocbebV+a7u9Bbst/Y2rV8PVprpATlqj4YOjqrNx
        v5MrLgyknNKUIqhbJXAy9j74x8OO1tilH6vf32zapZa/GtHpTvo7nRr1pNnfUgbp
        vBCvXoxIrg7rrWx3kjRF9Cri1d5khUDXYJzewflSsgYLLTygQ+lwthw+XghdHNos
        TARNSRPrO5JsWmSc6R9bjcuyhAsxvhAS1LpE1EwckkMUgSvdfmKbNc3RkjyusGYP
        Nlo+MiECpArwqymOxnULpKCwgJApVrwht0eDYzIw5XCe68FCQ/Ewaj25l81gVyWQ
        gM4KvdmCt0vk++15mcuUayTdcUg4cAGegvP8g0a9qncHT83J9E4D47QvftZkqZtF
        E3e+hb4BEdtJoedF9IHxjaHpRVhwJT98
        -----END CERTIFICATE-----
        -----BEGIN CERTIFICATE-----
        MIIFhzCCA2+gAwIBAgIQGjdQ3OTSYx62oSmGTy9tazANBgkqhkiG9w0BAQwFADBM
        MQswCQYDVQQGEwJHQjEMMAoGA1UEChMDbmhzMQswCQYDVQQLEwJDQTEiMCAGA1UE
        AxMZTkhTIFBUTCBSb290IEF1dGhvcml0eSBHMjAeFw0yMjA4MDQxNDA1NDNaFw0z
        MjA4MDQxNDM1NDNaMEwxCzAJBgNVBAYTAkdCMQwwCgYDVQQKEwNuaHMxCzAJBgNV
        BAsTAkNBMSIwIAYDVQQDExlOSFMgSU5UIEF1dGhlbnRpY2F0aW9uIEcyMIIBIjAN
        BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxT9GjD+It1PZUGSCxqgZl0GFu1Bs
        T2+IrzTQP0PnI0GQSEVmln4629ezXxhPigPqokzw4lDS/x5a/1qcSVMzgPBkaYH8
        04+MEBQNatuZhEu6zJPr6ARR3kGEf6MfxyllL5FwxU7AYNuACb6eVKvST/OC40Vx
        CGEhoIwvhvA016K50wYwtv8oiaywpHx+NbD2VhdOOsHNHZIauOmqHzY3IwmvS5NA
        NiZx8s8ctETbRsrwgO3p/667ix3PZME9yCPmzhm9TsyJABEjIDrRm1qW15V+GNfz
        jjBkN+j5dmtJRHbO+KLwwqY63sHg3JNeA74FFxxfVlSwUykeuQTT8UbcbwIDAQAB
        o4IBYzCCAV8wDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwPgYD
        VR0gBDcwNTAzBgsqhjoAiXtlAAMCADAkMCIGCCsGAQUFBwIBFhZodHRwczovL3Br
        aS5uaHMudWsvQ1BTMHgGCCsGAQUFBwEBBGwwajAjBggrBgEFBQcwAYYXaHR0cDov
        L29jc3AubmhzLnVrL29jc3AwQwYIKwYBBQUHMAKGN2h0dHA6Ly9wa2kubmhzLnVr
        L1BUTC9HMi9yb290L05IU1BUTFJvb3RBdXRob3JpdHlHMi5jcnQwPwYDVR0fBDgw
        NjA0oDKgMIYuaHR0cDovL2NybC5uaHMudWsvUFRML0cyL3Jvb3QvTkhTUFRMcm9v
        dEcyLmNybDAfBgNVHSMEGDAWgBT1ttVSqL14/nJhaztdjCPAsBYM8zAdBgNVHQ4E
        FgQUFsdHBKhgyeRdq5nylPfD3jOY1CIwDQYJKoZIhvcNAQEMBQADggIBAEWWjN0d
        6uxtKi5aLEv0CtUXqg7MJClCHKwCpYuewzI/OfRux5LuL7xHQx8Baj5Jh2IiZLkc
        vPQ626RVnKaYOvJAoM7UWMFgr3vta0uMEAnxRIOCpNiQFDh4HBpzbQNcMg8zkKUi
        JMb4OmT09zCzGTG2WdPT6KwAJOXw9IVeT+Z8ggScCmbiLKHT+s9y612oekIH0SxM
        /BNjmyYWt02cON6e92XXs6refjoJS29Kne2nBwersk1bLAumcueVBEtnMUBILXlH
        XoFcCIZSOca/qg9K7jyxl+uyXWK74AblMi0RfKsziM34Ux+hKv03SknLT9kbIBt0
        lbjntoeweu4oXMDQ+wdjSRe0OM0Ed2ttFMsI8jSkJAQlvN1uks5/M+cdAsg3D7Gp
        Df3WPHCT17ulr9VJ5I16XOb6JnNoMGEgUQm/AyNGO2zLm+XLo4Ujk/dKES08Cwwm
        zjXqOCti2Kp9mWYF8x1gOwIu4ye+rBhJdlNnxvbdV4oOyo1CYyw261jWI19yCaDJ
        Hmgq1F8M7nY0C9NRqlRaB1G+p1+mZVlVMOOD6EmprV80rBDfVN/N2swbmSGhijNe
        zAlqBMIkp6jTG9lEJbvtpY6aGWGlEheb2pPcBCXcBknI1Lhqv/sgdM6zbkzD+rAi
        oukkF6E6wLgCHgPz3FJwVBnM0NdaISHTBbOQ
        -----END CERTIFICATE-----
      - MHS_INBOUND_QUEUE_BROKERS=amqp://localhost:5672
      - MHS_INBOUND_QUEUE_NAME=inbound
      - MHS_SECRET_INBOUND_QUEUE_USERNAME=guest
      - MHS_SECRET_INBOUND_QUEUE_PASSWORD=guest
      - MHS_STATE_TABLE_NAME=mhs_state
      - MHS_SYNC_ASYNC_STATE_TABLE_NAME=sync_async_state
      - MHS_DB_ENDPOINT_URL=http://localhost:8000
      - MHS_INBOUND_QUEUE_MESSAGE_TTL_IN_SECONDS=0
      # boto3 requires some AWS creds to be provided, even
      # when connecting to local DynamoDB
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - MHS_INBOUND_USE_SSL=false
      #      - TCP_PORTS=443
      - SERVICE_PORTS=80
      - SUPPORTED_FILE_TYPES
  outbound:
    image: nhsdev/nia-mhs-outbound:1.3.3
    ports:
      - "32768:80"
    environment:
      - MHS_LOG_LEVEL=DEBUG
      - MHS_SECRET_PARTY_KEY=VND3J-823806
      - MHS_SECRET_CLIENT_CERT:client_cert.pem
      - MHS_SECRET_CLIENT_KEY:|
          -----BEGIN PRIVATE KEY-----
            MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/eldvdphgPbqf
            FcMEmoom173g7ptz7iHMxvAXwEBz1+oY/WCgOt/9DAUYLWkpjX7NbMuk6biZ2PQL
            fyWXjxj5OKzW76bqoZnb2kYoBuQYx+Nj3hhNC3Qnrxbnx7IzzK/qCNa+SzOVbVjf
            eOPTy6VIicEMLjp5GYcyJ/c1gsZPwASxsLo71ieAbiy18m/wgiDvY+dQ8YjN6k+Z
            xsrRrjjyF7iCOFdMg8C4Rdtz7ik2TRltrE1AngkZVV4EOsdJffDblfxLD4qvVdRW
            wLdzoMh1pc9TjdmXyrAutsfe5NOR+RbffHSARXFW5fb7xI1Y/B1GmSBFMCAC+uiU
            QvXhaZcrAgMBAAECggEAILeIxRTgiGFDx/bx8ZFuVaC7YvmiOjbQM6syTvychq63
            4zk4D2i/6P7qx+zKcT0qE3OpgC4nSrJVULmS9MiQndTfQ4KDZMfkADrVjfVPeCR/
            aAsE3/U7DaTPJx9qBYvN6xFDkBRNZhTfAKApXYEIZtKS17/2YcbI4PsPNGd59xou
            df7zgbd6SA47pAHoregeaRcsMIztqtjf3UhYe4WoqHZFKUvTkxgPbs7E1p5TZ92g
            RslTdDbQqLaHdiTOqKB/g363qhJ5dVVm+rb6MjtgJGdnpLVH5XxuboECXF4FRJR3
            StrM2HGSB1z7ZeasNiKtT63kMO7QKiA5TyltzwHM0QKBgQDns/3bNqYfuhWCdvwq
            W0oON9OKAByWRIuwWzIQWIQUm2szwH2fgUJB2V3/AXD/y2SEdQZM3A0L0xBhVTQj
            cc2nvL7p6J+oiYp2GUHm73tHpkAzq7hbA6ANRGRmRD2pIUjOL5qPbtwM+gfGTpcN
            mjUYGfw1ggk0LOZHn+4sSVANnwKBgQDTjoPhPtI1O8up91NBbSXeSp3qMWUa9dtK
            eLB8wEKCBWdlFL0fD1hMjmJEqaY4UZm1Gs/sbDIkGogahmsS6lEiTWFbEK6gFUTY
            dCJ65WhuqdLKyvkwmr4694Ctp6Ejhbod/2/2GBPhWLrUTAQSZ4TH8Zp/KJZSXsgl
            4jVO6Syy9QKBgQDXhI1I/RESi8T8IG63e0hr5zOFtkrg3wtL09fCaoMYo+PYNGDl
            H5cgpu4OhymzVF2/8xYUIc6kxAMFdfpUScOwFRlDe1QesSiwZxfsla8G2zX2mfCV
            /8486PO2SB1Olx4gYxkR910JWPwoUeuhBGIEdA8rOjQTavwbfUBNwzeKIwKBgFka
            lntBbWIUfFRrIjrVUPTOcrKX+WCgmqtEJ/lzNM/0nLbbREiXuvYLpmILHkJsRBQe
            ZeLLM1c3gYnCgcimvmN3OgEUBqjQLH4KdBdVFmY9ytW1Jb2N/39wjVcW2mzOvzQx
            SSPawkzQhWgzWCe0SB26qfrSynWJDD3Ah/ljhnsdAoGAaCDlZ/N/BPvMWfafyGXg
            Zr1iEso3Vzulr3/UwasqdbURVKbglhWzdTuZMwiPjhbrVcPDZzpg02uHHM7UXtBI
            g83mz0maeg1cRE6ftVMRQULcrdF1hJ44db0oHbA7FRODBJhIazPtLPVAXY+j57KA
            1vsiWMuSqmPRbL5yiaY2QVc=
            -----END PRIVATE KEY-----
      - MHS_SECRET_CA_CERTS:ca_certs.pem
      - MHS_STATE_TABLE_NAME=mhs_state
      - MHS_DB_ENDPOINT_URL=http://host.docker.internal:8000
      - MHS_SYNC_ASYNC_STATE_TABLE_NAME=sync_async_state
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - MHS_RESYNC_INTERVAL=1
      - MAX_RESYNC_RETRIES=20
      - MHS_SPINE_ROUTE_LOOKUP_URL=http://localhost:8080/route
      - MHS_SPINE_ORG_CODE=YES
      - MHS_SPINE_REQUEST_MAX_SIZE=4999600 # 5 000 000 - 400
      # Note that this endpoint URL is Opentest-
      - MHS_FORWARD_RELIABLE_ENDPOINT_URL=https://msg.int.spine2.ncrs.nhs.uk/reliablemessaging/reliablerequest
      # This is for disabling hostname validation so OpenTest ip address
      - MHS_OUTBOUND_VALIDATE_CERTIFICATE=${MHS_OUTBOUND_VALIDATE_CERTIFICATE:-True}
      - SERVICE_PORTS=80
      - MHS_OUTBOUND_ROUTING_LOOKUP_METHOD=SDS_API
      - MHS_SDS_API_URL=https://int.api.service.nhs.uk/spine-directory/FHIR/R4
      - MHS_SDS_API_KEY=BGH3LMDtnadxNtL6YetqurpZDnE4wjtz
  route:
    image: nhsdev/nia-mhs-route:1.3.3
    ports:
      - "8080:80"
    environment:
      - MHS_LOG_LEVEL=NOTSET
      - MHS_SDS_URL=ldap://192.168.128.11
      - MHS_SDS_SEARCH_BASE=ou=services,o=nhs
      - MHS_DISABLE_SDS_TLS=True
      - MHS_SDS_REDIS_CACHE_HOST=redis
      - MHS_SDS_REDIS_DISABLE_TLS=True
  dynamodb:
    container_name: host.docker.internal
    image: nhsdev/nia-dynamodb-local:latest
    ports:
      - "8000:8000"
  mongodb:
    image: mongo:5.0.16
    ports:
      - "27018:27018"
  rabbitmq:
    image: nhsdev/nia-rabbitmq-local:latest
    ports:
      - "15672:15672"
      - "5672:5672"
    hostname: "localhost"
  redis:
    image: redis
    ports:
      - "6379:6379"

  inbound-lb:
    image: dockercloud/haproxy
    links:
      - inbound
    ports:
      - "443:443"
      - "8079:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MODE=tcp
      - TIMEOUT=connect 0, client 0, server 0

  outbound-lb:
    image: dockercloud/haproxy
    links:
      - outbound
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TIMEOUT=connect 0, client 0, server 0

  sds-api-mock:
    build: ./docker/sds-api-mock
    ports:
      - "8081:8080"
    command:
      - -global-response-templating
      - --verbose