# Ports for MHS services
MHS_OUTBOUND_SERVER_PORT: "80"
MHS_SPINE_ROUTE_LOOKUP_SERVER_PORT: "8088"
MHS_INBOUND_HEALTHCHECK_SERVER_PORT: "8082"

# Common environment variables for outbound
MHS_OUTBOUND_VALIDATE_CERTIFICATE: "True"
MHS_OUTBOUND_ROUTING_LOOKUP_METHOD: "SPINE_ROUTE_LOOKUP"
MHS_SDS_API_URL: https://sandbox.api.service.nhs.uk/spine-directory/FHIR/R4
MHS_SDS_API_KEY: BGH3LMDtnadxNtL6YetqurpZDnE4wjtz

MHS_LOG_LEVEL: DEBUG

# Inbound queue configuration
MHS_INBOUND_QUEUE_BROKERS: amqp://localhost:5672,amqp://localhost:1234
MHS_INBOUND_QUEUE_NAME: "inbound"
MHS_INBOUND_QUEUE_MAX_RETRIES: "3"
MHS_INBOUND_QUEUE_RETRY_DELAY: "500"

# DynamoDB configuration
MHS_STATE_TABLE_NAME: mhs_state
MHS_SYNC_ASYNC_STATE_TABLE_NAME: sync_async_state
MHS_PERSISTENCE_ADAPTOR: "dynamodb"
MHS_DB_ENDPOINT_URL: http://host.docker.internal:8000

## AWS credentials
#AWS_ACCESS_KEY_ID: "test"
#AWS_SECRET_ACCESS_KEY: "test"

# Resync configuration
MHS_RESYNC_INTERVAL: "1"
MAX_RESYNC_RETRIES: "20"

# Spine routing lookup
MHS_SPINE_ROUTE_LOOKUP_URL: "http://localhost:8088"
MHS_SPINE_ORG_CODE: "YES"
MHS_SPINE_REQUEST_MAX_SIZE: "4999600"

# Forwarding configuration
MHS_FORWARD_RELIABLE_ENDPOINT_URL: https://msg.int.spine2.ncrs.nhs.uk/reliablemessaging/reliablerequest
MHS_SDS_URL: ldap://192.168.128.11 # SDS address from OpenTest
MHS_SDS_SEARCH_BASE: ou=services,o=nhs
MHS_DISABLE_SDS_TLS: "True"
MHS_SDS_REDIS_CACHE_HOST: redis
MHS_SDS_REDIS_DISABLE_TLS: "True"
MHS_LDAP_CONNECTION_RETRIES: "3"


#User-specific env variables
MHS_SECRET_PARTY_KEY: VND3J-823806
MHS_SECRET_CLIENT_CERT: mhs/client_cert.pem
MHS_SECRET_CLIENT_KEY: mhs/client_key.pem
MHS_SECRET_CA_CERTS: mhs/ca_certs.pem
FAKE_SPINE_PRIVATE_KEY: qwe
FAKE_SPINE_CERTIFICATE: qwe
FAKE_SPINE_CA_STORE: qwe
FAKE_SPINE_PORT: "8080"